name = input ("Zadaj meno:")
age = input ("Zadaj vek:")
nat = input ("Zadaj odkial si:")
food = input ("Co mas rad na jedenie?")
print (name)
print (age)
print (nat)
print (food)
print ("Ahoj",name)
print ("Máš", age, "rokov")
print ("Si z mesta", nat)
print ("Mas rad na jedenie", food)
